# Generated by Django 5.0.4 on 2024-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
