# Generated by Django 5.0.4 on 2024-09-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
