# Generated by Django 5.0.4 on 2024-08-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0004_userface'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFace',
        ),
    ]
