# Generated by Django 5.0.4 on 2024-08-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
