# Generated by Django 5.0.4 on 2024-09-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecognition', '0004_customuser_branch_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_encoding',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
