# Generated by Django 5.0.4 on 2024-08-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecognition', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_encoding',
            field=models.JSONField(default=list),
        ),
    ]
